name: icatchfoxes
favicon: null
layout_spectrum: 0.4357683
typography_spectrum: 0.01519067
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4e7e5'
    - '#080806'
    - '#6b7574'
    - '#8fb8b1'
    - '#0a506b'
  brandStrength: 0.7544803
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
